language: php

php:
  - 5.6

matrix:
  include:
    - php: 5.6
      env: TYPO3_BRANCH=master INTEGRATION=master COVERAGE=1

notifications:
  email:
    - moox@dcn.de

before_script:
  - cd ..
  - git clone --single-branch --branch master --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - sudo apt-get install parallel
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv moox_core typo3conf/ext/

script:
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
        if ! find typo3conf/ext/moox_core -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
            grep -v \"No syntax errors detected in\" /tmp/errors;
            exit 99;
        fi
    "
